[package]
authors = ["Ockam Developers"]
categories = ["cryptography", "asynchronous", "authentication","peer-to-peer", "network-programming"]
description = "Ockam Node implementation crate"
edition = "2018"
keywords = ["ockam", "crypto", "p2p", "async", "distributed"]
license = "Apache-2.0"
name = "ockam_node"
version = "0.5.0"

[dependencies]
ockam_core = {path = "../ockam_core", version = "0"}
tokio = {version = "1.4.0", features = ["full"]}
tracing = "0.1"
tracing-subscriber = { version = "0.2", features = ["fmt", "env-filter"] }
