[package]
name = "ockam_vault"
version = "0.0.0"
authors = ["Ockam Developers"]
edition = "2018"
license = "Apache-2.0"

[lib]
crate-type = ["rlib"]

[dependencies]
ockam_core = {path = "../ockam_core", version = "*"}
ockam_macro = {path = "../ockam_macro", version = "*"}
ockam_vault_core = {path = "../ockam_vault_core", version = "*"}
sha2 = "0.9"
hashbrown = "0.9.1"
zeroize = { version = "1.1", features = ["zeroize_derive"] }

[dev-dependencies]
hex = "0.4"
