[package]
authors = ["Ockam Developers"]
edition = "2018"
name = "ockam-worker"
version = "0.1.0"

[lib]
crate-type = ["staticlib", "rlib", "cdylib"]

[profile.release]
lto = true

[features]
default = []

[dependencies]
ockam = { version = "0.1", path = "../ockam"}
ockam-common = { version = "0.1", path = "../common" }
ockam-router = { version = "0.1", path = "../router"}
hashbrown = "0.9"

[dev-dependencies]
hex = "0.4"
