# Reference https://doc.mergify.io/configuration.html

queue_rules:
  - name: test

pull_request_rules:
  - name: automatic rebase and queue on approval
    actions:
      queue:
        name: test
        method: rebase
        update_method: rebase
        require_branch_protection: true
    conditions:
      - base=test
      - label=auto-merge
