
version: 2
updates:

  # Maintain dependencies for elixir ockam application
  - package-ecosystem: "mix"
    directory: "/implementations/elixir/ockam"
    commit-message:
      prefix: "build:"
    schedule:
      interval: "daily"

  # Maintain dependencies for elixir ockam_node_web application
  - package-ecosystem: "mix"
    directory: "/implementations/elixir/ockam_node_web"
    commit-message:
      prefix: "build:"
    schedule:
      interval: "daily"

  # Maintain dependencies for elixir ockam_transport_udp application
  - package-ecosystem: "mix"
    directory: "/implementations/elixir/ockam_transport_udp"
    commit-message:
      prefix: "build:"
    schedule:
      interval: "daily"

  # Maintain dependencies for elixir ockam_vault_software application
  - package-ecosystem: "mix"
    directory: "/implementations/elixir/ockam_vault_software"
    commit-message:
      prefix: "build:"
    schedule:
      interval: "daily"

  # Maintain dependencies for cargo
  - package-ecosystem: "cargo"
    directory: "/implementations/rust"
    commit-message:
      prefix: "build:"
    schedule:
      interval: "daily"
