# Reference https://doc.mergify.io/configuration.html

queue_rules:
  - name: default
    conditions: []

pull_request_rules:
  - name: enque for merge to develop
    conditions:
      - base=develop
      - label=auto-merge
      - or:
          - author=mrinalwadhwa
          - and:
            - "approved-reviews-by=@approvers"
            - "#approved-reviews-by>=1"
            - "#changes-requested-reviews-by=0"
    actions:
      queue:
        name: default
        method: rebase
        update_method: rebase
        require_branch_protection: true
