name: $name
on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths
    paths:
<% paths.each { println "      - '${it}'" } %>

jobs:
  $name:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ockam-network/ockam/builder@sha256:a4ee49a588dffbaef61eba29b4de0fe0be134b84aac3ab2f634ad92c74fe3802
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - id: $name
        working-directory: $wd
        run: $command
