[package]
name = "truck"
version = "0.1.0"
authors = ["Ockam Developers"]
edition = "2018"

[profile.release]
lto = true

[dependencies]
ockam = { version = "0.1", path = "../../ockam" }
ockam-transport = { version = "0.1", path = "../../transport" }