# This file configures an azure build pipeline
# https://docs.microsoft.com/en-us/azure/devops/pipelines/

name: $(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

pool: 'OckamHosted'

steps:
  - script: ./gradlew clean
    displayName: Clean

  - script: ./gradlew build
    displayName: Build

  - script: ./gradlew test
    displayName: Test

  - script: ./gradlew clean
    displayName: Clean
