[package]
name = "xeddsa"
version = "0.1.0"
authors = ["Ockam Developers"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
curve25519-dalek = "3.0"
ed25519-dalek = "1.0"
rand = "0.7"
sha2 = "0.9"
subtle = "2.3"
x25519-dalek = "1.1"
