[package]
name = "ockam_key_exchange_core"
version = "0.1.2"
authors = ["Ockam Developers"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_key_exchange_core"
readme = "README.md"
categories = ["cryptography", "asynchronous", "authentication","embedded", "no-std"]
keywords = ["ockam", "crypto", "kex", "cryptography", "encryption", "iot"]
description = """The Ockam Key Exchange trait.
"""

[dependencies]
ockam_core = { version = "0.8.0", path = "../ockam_core" }
ockam_vault_core = { version = "0.3.3", path = "../ockam_vault_core" }
zeroize = { version = "1.1", features = ["zeroize_derive"] }
