[package]
name = "examples"
version = "0.1.0"
authors = ["Ockam Developers"]
edition = "2018"

[dependencies]
ockam = {path = "../../ockam/ockam", version = "*"}
ockam_node_std = {path = "../../ockam/ockam_node_std", version = "*"}
executor = {version = "*"}
