[package]
name = "ockam_vault_test_suite"
categories = ["cryptography", "asynchronous", "authentication","network-programming", "embedded"]
description = """Ockam is a library for building devices that communicate securely, privately
and trustfully with cloud services and other devices.
"""
version = "0.1.2"
authors = ["Ockam Developers"]
edition = "2018"
license = "Apache-2.0"
keywords = ["ockam", "crypto", "cryptography", "network-programming", "encryption"]
readme = "README.md"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_vault_test_suite"

[dependencies]
ockam_core = {path = "../ockam_core", version = "0.11.1"}
ockam_vault_core = {path = "../ockam_vault_core", version = "0.5.1"}
