name: CARGO_TARGET_DIR Cache
description: CARGO_TARGET_DIR Cache
runs:
  using: "composite"
  steps:
    - uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed
      with:
        path: target
        key: cache-cargo-target----${{ github.workflow }}-${{ github.job }}-ghcr.io/ockam-network/ockam/builder@sha256:a7d3dca4d7ec4385a12a81534524831030650aeb8dc4e820733e6bdb9e6bfd6a-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: cache-cargo-target-${{ github.workflow }}-${{ github.job }}-ghcr.io/ockam-network/ockam/builder@sha256:a7d3dca4d7ec4385a12a81534524831030650aeb8dc4e820733e6bdb9e6bfd6a-

# https://doc.rust-lang.org/cargo/guide/build-cache.html
