[package]
name = "ockam-router"
version = "0.1.0"
authors = ["Ockam Developers"]
edition = "2018"

[lib]
crate-type = ["rlib"]

[profile.release]
lto = true

[dependencies]
ockam = { version = "0.1", path = "../ockam" }
ockam-common = { version = "0.1", path = "../common" }

