[package]
name = "ockam_key_exchange_xx"
version = "0.1.4"
authors = ["Ockam Developers"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://github.com/ockam-network/ockam"
repository = "https://github.com/ockam-network/ockam/tree/develop/implementations/rust/ockam/ockam_key_exchange_xx"
readme = "README.md"
categories = ["cryptography", "asynchronous", "authentication","embedded", "no-std"]
keywords = ["ockam", "crypto", "xx", "cryptography", "encryption"]
description = """The Ockam Noise XX impementation.
"""

[dependencies]
ockam_core = { path = "../ockam_core", version = "0.11.0" }
ockam_vault_core = { path = "../ockam_vault_core", version = "0.4.1" }
ockam_vault_sync_core = { version = "0.1.0", path = "../ockam_vault_sync_core" }
ockam_key_exchange_core = { version = "0.1.4", path = "../ockam_key_exchange_core" }
zeroize = { version = "1.1", features = ["zeroize_derive"] }

[dev-dependencies]
ockam_vault = { path = "../ockam_vault", version = "0" }
ockam_node = { path = "../ockam_node" , version = "0" }
