[package]
name = "truck"
version = "0.1.0"
authors = ["Ockam Developers"]
edition = "2018"

[profile.release]
lto = true

[dependencies]
colored = "2.0"
rand = "0.7"
ockam = { path = "../../../ockam/ockam" }
ockam_vault = { path = "../../../ockam/ockam_vault"}
ockam_key_exchange_core = { path = "../../../ockam/ockam_key_exchange_core" }
ockam_key_exchange_x3dh = { path = "../../../ockam/ockam_key_exchange_x3dh" }
okta-plugin = { path = "../" }
serde = "1.0"
serde_json = "1.0"

