[package]
name = "ockam_macros"
version = "0.1.0"
authors = ["Ockam Developers"]
edition = "2018"

[lib]
proc-macro = true

[features]
default = []
async = []
executor_async = ["async", "executor"]

[dependencies]
executor = {version = "*", optional = true}

