name: cargo_update_check
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  cargo_update_check:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ockam-network/ockam/builder@sha256:a4ee49a588dffbaef61eba29b4de0fe0be134b84aac3ab2f634ad92c74fe3802
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - name: Update and Check Ockam Example
        working-directory: examples/rust/get_started
        run: |
          rm -rf Cargo.lock
          cargo update
          cargo check
