name: Continuous Integration
on: [push, pull_request]

jobs:
  build_in_docker:
    name: Build in Docker
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ockam-network/ockam/builder@sha256:25ccb6651fa168460ae50548794135ba2eb80ae4b253055a478c05ba1baa1687
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - id: Lint
        run: ./gradlew lint

      - id: Build
        run: ./gradlew build

      - id: Test
        run: ./gradlew test

      - id: Clean
        run: ./gradlew clean
