name: Continuous Integration
on: [push, pull_request]

jobs:

  lint_rust:
    name: Lint Rust
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ockam-network/ockam/builder@sha256:d70b384ff4d40e403f9b5b171eada3ed6746117a9267e98ae530336747895fe2
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - id: Lint
        run: ./gradlew lint_rust

  lint_elixir:
    name: Lint Elixir
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ockam-network/ockam/builder@sha256:d70b384ff4d40e403f9b5b171eada3ed6746117a9267e98ae530336747895fe2
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - id: Lint
        run: ./gradlew lint_elixir

  build_rust:
    name: Build Rust
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ockam-network/ockam/builder@sha256:d70b384ff4d40e403f9b5b171eada3ed6746117a9267e98ae530336747895fe2
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - id: Build
        run: ./gradlew build_rust

  build_elixir:
    name: Build Elixir
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ockam-network/ockam/builder@sha256:d70b384ff4d40e403f9b5b171eada3ed6746117a9267e98ae530336747895fe2
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - id: Build
        run: ./gradlew build_elixir

  test_rust:
    name: Test Rust
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ockam-network/ockam/builder@sha256:d70b384ff4d40e403f9b5b171eada3ed6746117a9267e98ae530336747895fe2
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - id: Test
        run: ./gradlew test_rust

  test_elixir:
    name: Test Elixir
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ockam-network/ockam/builder@sha256:d70b384ff4d40e403f9b5b171eada3ed6746117a9267e98ae530336747895fe2
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - id: Test
        run: ./gradlew test_elixir
