name: Lint Commit Messages
on: push

jobs:
  commitlint:
    name: Commitlint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
        with:
          fetch-depth: 0

      - name: Commitlint
        uses: wagoid/commitlint-github-action@1788ebdc06fd21e83bfd5e93c8e486a837cf401d # v2.1.6
