name: Build in Docker
on: [push, pull_request]

jobs:
  build_in_docker:
    name: Build in Docker
    runs-on: ubuntu-20.04
    container:
      image: ockam/builder:latest@sha256:5d19913e014f4e3158be63569ac03a628646d9b2549d36b280c5fc296c01d830
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - id: Lint
        run: ./gradlew lint

      - id: Build
        run: ./gradlew build

      - id: Test
        run: ./gradlew test

      - id: Clean
        run: ./gradlew clean
