name: Lint Editorconfig
on: [push, workflow_dispatch]

jobs:
  editorconfig_lint:
    name: Editorconfig
    runs-on: ubuntu-20.04
    container:
      image: greut/eclint:v0.3.2@sha256:9e1d4d36f1c8ee9982e60266d984d9eb9ffdd3fc04cd2e0e70fbbbf8fd7d1f0f
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - name: Lint Editorconfig
        run: eclint -color=always
