name: Lint Editorconfig
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop

permissions:
  contents: read

jobs:
  editorconfig_lint:
    name: Editorconfig
    runs-on: ubuntu-20.04

    # https://gitlab.com/greut/eclint
    container:
      image: greut/eclint:v0.3.3@sha256:95e9a3dcbd236bae6569625cd403175cbde3705303774e7baca418b6442b8d77

    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Lint Editorconfig
        run: eclint -color=always
