name: Lint Editorconfig
on: push

jobs:
  editorconfig_lint:
    name: Editorconfig
    runs-on: ubuntu-20.04
    container:
      image: greut/eclint:v0.3.0@sha256:99ba8a550571b6ecb3fe360d715eda7e9548fe1990a4a5120e228c1cf2cb7d6b
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - name: Lint Editorconfig
        run: eclint -color=always
