name: Lint Editorconfig

# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#on
on:
  # Support running the workflow manually
  # https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch:
  # Trigger on Push or Pull Request to the develop branch
  # But prevent it from running twice
  # https://github.community/t/how-to-trigger-an-action-on-push-or-pull-request-but-not-both/16662/2
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

# Limit permissions to only read contents of the repository
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#permissions
permissions:
  contents: read

jobs:
  editorconfig_lint:
    name: Editorconfig
    runs-on: ubuntu-20.04

    # Stop a previous run, if a new run is triggered.
    # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-using-concurrency-to-cancel-any-in-progress-job-or-run
    concurrency:
      group: ${{ github.head_ref }}
      cancel-in-progress: true

    # https://gitlab.com/greut/eclint
    container:
      image: greut/eclint:v0.3.3@sha256:95e9a3dcbd236bae6569625cd403175cbde3705303774e7baca418b6442b8d77

    steps:
      - name: Checkout
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Lint Editorconfig
        run: eclint -color=always
