name: elixir_lint_ockam_ockam_node_web
on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths
    paths:
      - 'implementations/rust/ockam/ockam_ffi/**'
      - 'build.gradle'
      - 'implementations/elixir/build.gradle'
      - 'settings.gradle'
      - 'implementations/elixir/settings.gradle'
      - 'implementations/elixir/ockam/ockam_node_web/**'

jobs:
  elixir_lint_ockam_ockam_node_web:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ockam-network/ockam/builder@sha256:e382c8800a89ce43acb675131d9f30e74093d195a95047f87e9206a0c52c17a7
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - name: Generate random key
        run: echo RANDOM=$(date +%s) >> $GITHUB_ENV

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            /root/.gradle/caches
            /root/.gradle/wrapper
            implementations/elixir/ockam/ockam_node_web/_build
            implementations/elixir/ockam/ockam_node_web/deps
          key: ${{ runner.os }}-cache-${{ env.RANDOM }}
          restore-keys: ${{ runner.os }}-cache-

      - id: elixir_lint_ockam_ockam_node_web
        working-directory: implementations/elixir
        run: ../../gradlew lint_ockam_ockam_node_web
