name: Gradle
on:
  pull_request:
    paths:
      - '**.gradle'
      - 'tools/gradle/**'
      - 'gradlew'
      - 'gradlew.bat'
      - .github/workflows/gradle.yml
  push:
    paths:
      - '**.gradle'
      - 'tools/gradle/**'
      - 'gradlew'
      - 'gradlew.bat'
      - .github/workflows/gradle.yml
  schedule:
    - cron:  '0 1 * * *' # https://cron.help/#0_1_*_*_*
  workflow_dispatch:

permissions:
  contents: read

jobs:
  list_gradle_tasks:
    name: List Gradle Tasks
    strategy:
      matrix:
        # https://github.com/actions/virtual-environments#available-environments
        os: [ubuntu-20.04, macos-10.15, windows-2019]
        java: [8, 11, 16, 17]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup Java
        # https://github.com/actions/setup-java/releases/tag/v2.4.0
        uses: actions/setup-java@5f00602cd1b2819185d88dc7a1b1985f598c6705 # v2.4.0
        with:
          distribution: 'temurin'
          check-latest: true
          java-version: ${{ matrix.java }}

      - name: Checkout
        # https://github.com/actions/checkout/releases/tag/v2.4.0
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Generate random key
        run: echo RANDOM=$(date +%s) >> $GITHUB_ENV

      - name: Cache Gradle
        # https://github.com/actions/cache/releases/tag/v2.1.7
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed # v2.1.7
        with:
          path: |
            /root/.gradle/caches
            /root/.gradle/wrapper
          key: ${{ runner.os }}-cache-${{ env.RANDOM }}
          restore-keys: ${{ runner.os }}-cache-

      - name: List Tasks
        run: ./gradlew tasks --all
