[package]
name = "ockam"
version = "0.1.0"
authors = ["Ockam Developers"]
edition = "2018"

[lib]
crate-type = ["rlib"]

[dependencies]
ockam_node_attribute = {path = "../ockam_node_attribute", version = "*"}
hashbrown = "*"
executor = "*"

[dev-dependencies]
trybuild = {version = "1.0.38", features = ["diff"]}
